const PDFDocument = require('pdfkit');
const TestResult = require('../models/TestResult');
const fs = require('fs');

const pdfService = {
    generateReport: async (testId, res) => {
        const test = await TestResult.findById(testId).populate('user', 'name email');

        if (!test) {
            throw new Error('Test not found');
        }

        const doc = new PDFDocument();

        // Stream PDF to response
        doc.pipe(res);

        // Header
        doc.fontSize(25).text('Grapholyze Analysis Report', { align: 'center' });
        doc.moveDown();
        doc.fontSize(12).text(`Date: ${new Date(test.createdAt).toLocaleDateString()}`, { align: 'center' });
        doc.moveDown();

        // User Info
        doc.fontSize(16).text('User Information', { underline: true });
        doc.fontSize(12).text(`Name: ${test.user.name}`);
        doc.text(`Email: ${test.user.email}`);
        doc.moveDown();

        // Results
        doc.fontSize(16).text('Analysis Results', { underline: true });
        doc.moveDown();

        doc.fontSize(20).fillColor('#6366f1').text(test.results.personalityType);
        doc.fontSize(12).fillColor('black').text(`Confidence Score: ${(test.results.confidence * 100).toFixed(1)}%`);
        doc.moveDown();

        doc.fontSize(14).text('Detected Traits:');
        test.results.traits.forEach(trait => {
            doc.text(`• ${trait}`, { indent: 20 });
        });

        // Footer
        doc.moveDown(4);
        doc.fontSize(10).text('Generated by Grapholyze AI', { align: 'center', color: 'grey' });

        doc.end();
    },
};

module.exports = pdfService;
